export const ADD_BOOK = "ADD_BOOK";
export const ADD_BOOK_OK = "ADD_BOOK_OK";
export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";

export const GET_BOOK_TO_UPDATE = "GET_BOOK_UPDATE";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const UPDATE_BOOK_OK = "UPDATE_BOOK_OK";
export const UPDATE_BOOK_ERROR = "UPDATE_BOOK_ERROR";

export const LIST_BOOKS = "LIST_BOOKS";
export const LIST_BOOKS_OK = "LIST_BOOKS_OK";
export const LIST_BOOKS_ERROR = "LIST_BOOKS_ERROR";

export const SELECT_BOOK = "SELECT_BOOK";
export const SELECT_BOOK_OK = "SELECT_BOOK_OK";
export const SELECT_BOOK_ERROR = "SELECT_BOOK_ERROR";

export const GET_BOOK = "GET_BOOK";
export const GET_BOOK_OK = "GET_BOOK_OK";
export const GET_BOOK_ERROR = "GET_BOOK_ERROR";

export const ADD_AUTHOR = "ADD_AUTHOR";
export const ADD_AUTHOR_OK = "ADD_AUTHOR_OK";
export const ADD_AUTHOR_ERROR = "ADD_AUTHOR_ERROR";

export const GET_AUTHOR_TO_EDIT = "GET_AUTHOR_TO_EDIT";
export const UPDATE_AUTHOR = "EDIT_AUTHOR";
export const UPDATE_AUTHOR_OK = "UPDATE_AUTHOR_OK";
export const UPDATE_AUTHOR_ERROR = "UPDATE_AUTHOR_ERROR";

export const LIST_AUTHORS = "LIST_AUTHORS";
export const LIST_AUTHORS_OK = "LIST_AUTHORS_OK";
export const LIST_AUTHORS_ERROR = "LIST_AUTHORS_ERROR";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_OK = "ADD_CATEGORY_OK";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";

export const LIST_CATEGORIES = "LIST_CATEGORIES";
export const LIST_CATEGORIES_OK = "LIST_CATEGORIES_OK";
export const LIST_CATEGORIES_ERROR = "LIST_CATEGORIES_ERROR";

export const ADD_PUBLISHER = "ADD_PUBLISHER";
export const ADD_PUBLISHER_OK = "ADD_PUBLISHER_OK";
export const ADD_PUBLISHER_ERROR = "ADD_PUBLISHER_ERROR";

export const LIST_PUBLISHERS = "LIST_PUBLISHERS";
export const LIST_PUBLISHERS_OK = "LIST_PUBLISHERS_OK";
export const LIST_PUBLISHERS_ERROR = "LIST_PUBLISHERS_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_OK = "SIGN_UP_OK";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_OK = "GET_USER_OK";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_OK = "UPDATE_USER_OK";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const SUBSCRIBE_USER = "SUBSCRIBE_USER";
export const SUBSCRIBE_USER_OK = "SUBSCRIBE_USER_OK";
export const SUBSCRIBE_USER_ERROR = "SUBSCRIBE_USER_ERROR";

export const UNSUBSCRIBE_USER = "UNSUBSCRIBE_USER";
export const UNSUBSCRIBE_USER_OK = "UNSUBSCRIBE_USER_OK";
export const UNSUBSCRIBE_USER_ERROR = "UNSUBSCRIBE_USER_ERROR";

export const GET_BOOK_RATING = "GET_BOOK_RATING";
export const GET_BOOK_RATING_OK = "GET_BOOK_RATING_OK";
export const GET_BOOK_RATING_ERROR = "GET_BOOK_RATING_ERROR";

export const ADD_BOOK_RATING = "ADD_BOOK_RATING";
export const ADD_BOOK_RATING_OK = "ADD_BOOK_RATING_OK";
export const ADD_BOOK_RATING_ERROR = "ADD_BOOK_RATING_ERROR";

export const GET_USER_CART = "GET_USER_CART";
export const GET_USER_CART_OK = "GET_USER_CART_OK";
export const GET_USER_CART_ERROR = "GET_USER_CART_ERROR";

export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const ADD_ITEM_CART_OK = "ADD_ITEM_CART_OK";
export const ADD_ITEM_CART_ERROR = "ADD_ITEM_CART_ERROR";

export const UPDATE_ITEM_CART = "UPDATE_ITEM_CART";
export const UPDATE_ITEM_CART_OK = "UPDATE_ITEM_CART_OK";
export const UPDATE_ITEM_CART_ERROR = "UPDATE_ITEM_CART_ERROR";

export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const REMOVE_ITEM_CART_OK = "REMOVE_ITEM_CART_OK";
export const REMOVE_ITEM_CART_ERROR = "REMOVE_ITEM_CART_ERROR";

export const CHECKOUT = "CHECKOUT";
export const CHECKOUT_OK = "CHECKOUT_OK";
export const CHECKOUT_ERROR = "CHECKOUT_ERROR";

export const GET_CLIENT_ORDERS = "GET_CLIENT_ORDERS";
export const GET_CLIENT_ORDERS_OK = "GET_CLIENT_ORDERS_OK";
export const GET_CLIENT_ORDERS_ERROR = "GET_CLIENT_ORDERS_ERROR";

export const SELECTED_ORDER = "SELECTED_ORDER";
export const SELECTED_ORDER_OK = "SELECTED_ORDER_OK";
export const SELECTED_ORDER_ERROR = "SELECTED_ORDER_ERROR";

export const LIST_SUBSCRIPTIONS = "LIST_SUBSCRIPTIONS";
export const LIST_SUBSCRIPTIONS_OK = "LIST_SUBSCRIPTIONS_OK";
export const LIST_SUBSCRIPTIONS_ERROR = "LIST_SUBSCRIPTIONS_ERROR";

export const REPORT = "REPORT";
export const REPORT_OK = "REPORT_OK";
export const REPORT_ERROR = "REPORT_ERROR";

export const ADD_DISCOUNT = "ADD_DISCOUNT";
export const ADD_DISCOUNT_OK = "ADD_DISCOUNT_OK";
export const ADD_DISCOUNT_ERROR = "ADD_DISCOUNT_ERROR";

export const LIST_DISCOUNTS = "LIST_DISCOUNTS";
export const LIST_DISCOUNTS_OK = "LIST_DISCOUNTS_OK";
export const LIST_DISCOUNTS_ERROR = "LIST_DISCOUNTS_ERROR";